(ns space-age)

(def earth-sec-in-year 31557600)
(def mercury-sec-in-year (* 0.2408467  earth-sec-in-year))
(def venus-sec-in-year   (* 0.61519726 earth-sec-in-year))
(def mars-sec-in-year    (* 1.8808158  earth-sec-in-year))
(def jupiter-sec-in-year (* 11.862615  earth-sec-in-year))
(def saturn-sec-in-year  (* 29.447498  earth-sec-in-year))
(def uranus-sec-in-year  (* 84.016846  earth-sec-in-year))
(def neptune-sec-in-year (* 164.79132  earth-sec-in-year))

(defn on-mercury [secs] (/ secs mercury-sec-in-year))
(defn on-venus   [secs] (/ secs venus-sec-in-year))
(defn on-earth   [secs] (/ secs earth-sec-in-year))
(defn on-mars    [secs] (/ secs mars-sec-in-year))
(defn on-jupiter [secs] (/ secs jupiter-sec-in-year))
(defn on-saturn  [secs] (/ secs saturn-sec-in-year))
(defn on-uranus  [secs] (/ secs uranus-sec-in-year))
(defn on-neptune [secs] (/ secs neptune-sec-in-year))
