
GET http://localhost:3000/hello

### 
GET http://localhost:3000/job/create

###
GET http://localhost:3000/job/list

###
GET http://localhost:3000/job/start?id=job-5

###
GET http://localhost:3000/job/stop?id=job-3
###
GET http://localhost:3000/job/suspend?id=job-4
###
GET http://localhost:3000/job/resume?id=job-4


