@port=3001
@baseUrl=http://localhost:3001

@jobId=job-2d73804e-fdc9-4a7f-8e06-fef74020e7d9
###

GET {{baseUrl}}/hello

###
GET {{baseUrl}}/bye

###
POST {{baseUrl}}/throw


###
POST {{baseUrl}}/bye
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### 
GET {{baseUrl}}/job/create

###
GET {{baseUrl}}/job/list

###
GET {{baseUrl}}/job/start?id={{jobId}}

###
GET {{baseUrl}}/job/stop?id={{jobId}}
###
GET {{baseUrl}}/job/suspend?id={{jobId}}
###
GET {{baseUrl}}/job/resume?id={{jobId}}


